class Mappings:
    """Class with mapping, one for the condensed games (cg) and another for the
    recap of the games (hl). The dictionaries' keys are the teams' names and
    the values are the keywords for each of the type of videos.
    """

    team_cg_map = {
        "Los Angeles Angels": "laa",
        "Houston Astros": "hou",
        "Oakland Athletics": "oak",
        "Toronto Blue Jays": "tor",
        "Atlanta Braves": "atl",
        "Milwaukee Brewers": "mil",
        "St. Louis Cardinals": "stl",
        "Chicago Cubs": "chc",
        "Arizona Diamondbacks": "ari",
        "Los Angeles Dodgers": "lad",
        "San Francisco Giants": "sf",
        "Cleveland Indians": "cle",
        "Miami Marlins": "mia",
        "New York Mets": "nym",
        "Pittsburgh Pirates": "pit",
        "Philadelphia Phillies": "phi",
        "Seattle Mariners": "sea",
        "Washington Nationals": "wsh",
        "Texas Rangers": "tex",
        "Tampa Bay Rays": "tb",
        "Boston Red Sox": "bos",
        "Cincinnati Reds": "cin",
        "Colorado Rockies": "col",
        "Kansas City Royals": "kc",
        "San Diego Padres": "sd",
        "Baltimore Orioles": "bal",
        "Detroit Tigers": "det",
        "Minnesota Twins": "min",
        "New York Yankees": "nyy",
        "Chicago White Sox": "cws",
    }

    team_hl_map = {
        "Arizona Diamondbacks": "d-backs",
        "Atlanta Braves": "braves",
        "Baltimore Orioles": "orioles",
        "Boston Red Sox": "red-sox",
        "Chicago Cubs": "cubs",
        "Chicago White Sox": "white-sox",
        "Cincinnati Reds": "reds",
        "Cleveland Indians": "indians",
        "Colorado Rockies": "rockies",
        "Detroit Tigers": "tigers",
        "Houston Astros": "astros",
        "Kansas City Royals": "royals",
        "Los Angeles Angels": "angels",
        "Los Angeles Dodgers": "dodgers",
        "Miami Marlins": "marlins",
        "Milwaukee Brewers": "brewers",
        "Minnesota Twins": "twins",
        "New York Mets": "mets",
        "New York Yankees": "yankees",
        "Oakland Athletics": "athletics",
        "Philadelphia Phillies": "phillies",
        "Pittsburgh Pirates": "pirates",
        "San Diego Padres": "padres",
        "San Francisco Giants": "giants",
        "Seattle Mariners": "mariners",
        "St. Louis Cardinals": "cardinals",
        "Tampa Bay Rays": "rays",
        "Texas Rangers": "rangers",
        "Toronto Blue Jays": "blue-jays",
        "Washington Nationals": "nationals",
    }
